SELECT DISTINCT gt.NOMBRE
FROM IHAIDWH1.V_G2R_F_USUA u
LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN_INTE gti ON u.ID_USUARIO = gti.ID_USUARIO
LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN_RESP gtr ON u.ID_USUARIO = gtr.ID_USUARIO
LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN gt ON gti.ID_GRUPO = gt.ID_GRUPO OR gtr.ID_GRUPO = gt.ID_GRUPO
WHERE gt.DELETED = 0 AND u.ID_ORGANIZACION IN (10, 20, 30) ;

SELECT DISTINCT u.MATRICULA, u.MATRICULA_DACFI, u.NOMBRE
FROM IHAIDWH1.V_G2R_F_USUA u
WHERE u.ID_ORGANIZACION IN (10, 20, 30) AND u.DELETED = 0;

SELECT DISTINCT u.MATRICULA, u.matricula_dacfi, u.NOMBRE
    FROM IHAIDWH1.V_G2R_F_USUA u
    LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN_INTE gti ON u.ID_USUARIO = gti.ID_USUARIO
    LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN_RESP gtr ON u.ID_USUARIO = gtr.ID_USUARIO
    LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN gt ON gti.ID_GRUPO = gt.ID_GRUPO OR gtr.ID_GRUPO = gt.ID_GRUPO
    WHERE gt.DELETED = 0 AND gt.NOMBRE = 'GROUP-3' AND u.ID_ORGANIZACION IN (10, 20, 30) AND u.DELETED = 0;

  SELECT DISTINCT gt.NOMBRE
    FROM IHAIDWH1.V_G2R_F_USUA u
    LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN_INTE gti ON u.ID_USUARIO = gti.ID_USUARIO
    LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN_RESP gtr ON u.ID_USUARIO = gtr.ID_USUARIO
    LEFT JOIN IHAIDWH1.V_G2R_F_GRP_TECN gt ON gti.ID_GRUPO = gt.ID_GRUPO OR gtr.ID_GRUPO = gt.ID_GRUPO
    WHERE gt.DELETED = 0 AND u.matricula= 'U2D123222' AND u.ID_ORGANIZACION IN (10, 20, 30) AND u.DELETED = 0 AND gt.ID_TIPO_GRUPO = 33;
 